apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2 
kind: Deployment 
metadata: 
  name: panquequenet
spec: 
  selector: 
    matchLabels: 
      app: panquequenet
  replicas: 2 # tells deployment to run 2 pods matching the template 
  template:
    metadata: 
      labels: 
        app: panquequenet
    spec: 
      containers: 
      - name: panquequenet
        image: panquequenet.azurecr.io/panquequenet:#{Build.BuildId}#
        ports: 
        - containerPort: 80 
--- 
# https://kubernetes.io/docs/concepts/services-networking/service/#defining-a-service  
kind: Service 
apiVersion: v1 
metadata: 
  name: panquequenet
spec: 
  selector: 
    app: panquequenet
  ports: 
  - protocol: TCP 
    port: 80 
    targetPort: 80 
  type: LoadBalancer 